remote_theme: pages-themes/cayman@v0.2.0

plugins:
 - jekyll-remote-theme

title: The Retreat
description: 4 song EP from A.Hughes and O.J.B.

# Analytics
analytics:
  provider: "google-gtag"
  google:
    measurement_id : "G-MTJKHFWTHN"
    anonymize_ip : # true, false (default)
